services:
  hoster:
    image: dvdarias/docker-hoster
    container_name: hoster
    restart: always
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock
      - /etc/hosts:/tmp/hosts
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_ALLOW_EMPTY_PASSWORD: "true"
    restart: unless-stopped
  redis:
    image: redis:8
    container_name: redis
    ports:
      - "127.0.0.1:6379:6379"
    restart: unless-stopped